platform:
  - amd64

environment:
  global:
    VSVER: 14
    my_secret:
      secure: YOioakwGPBD5jBTUnSD71Al48yWuURhnehlozjLZBuBxZZGM8wOpyc9dVgpJnK9n
    my_salt:
      secure: jQ+wp6UFUNOVoibd/aLmbj3lFRF2DPtC3EHNWDFxvVGWhM9OuvmJAfHScvvN1RXoiAbEZe0g3I6DOys1DRZbtg==

  matrix:
    - PYTHON: "C:\\Python36-x64"

install:
  - .\scripts\install.bat

build: off

test_script:
  - .\scripts\run_appveyor.bat
